require('dotenv').config()
const Client = require('./Client.js')
const { commandHandler } = require('./commandHandler.js')
const client = new Client()
client.login()
client.mongoConnect()
commandHandler()
client.once('ready', (...args) => require('./events/ready.js').execute(...args))
client.on('interactionCreate', (...args) => require('./events/interactionCreate.js').execute(...args, client))
client.on('messageCreate', (...args) => require('./events/messageCreate.js').execute(...args, client))
exports.client = client